### ISSUE TITLE
Semantic caching for RAG based chatbots

### ISSUE THREAD

**Issue by awsrk** [aws-samples/genai-quickstart-pocs#303]
Customers are looking for easy ways to cache similar questions/responses in their RAG systems. I'm looking to build a step functions based workflow which incorporates semantic caching utilizing opensearch and a postgressql database

**Comment by ryanadoty** [comment]
That sounds great! Any updates you can provide here would be great!

**Comment by flamingquaks** [comment]
This appears completed with the merge of #320. 
Closing Issue
